{
  "type": "record",
  "name": "ProductMoved",
  "namespace": "warehouse.events.v1",
  "doc": "Перемещение товара между зонами",
  "fields": [
    {"name": "event_id",    "type": "string"},
    {"name": "event_type",  "type": "string", "default": "PRODUCT_MOVED"},
    {"name": "timestamp",   "type": {"type": "long", "logicalType": "timestamp-millis"}},
    {"name": "product_id",  "type": "string"},
    {"name": "from_zone_id","type": "string"},
    {"name": "to_zone_id",  "type": "string"},
    {"name": "quantity",    "type": "long"}
  ]
}
