{
  "type": "record",
  "name": "OrderCreated",
  "namespace": "warehouse.events.v1",
  "doc": "Создание заказа со списком позиций (резервирует товары по позициям)",
  "fields": [
    {"name": "event_id",   "type": "string"},
    {"name": "event_type", "type": "string", "default": "ORDER_CREATED"},
    {"name": "timestamp",  "type": {"type": "long", "logicalType": "timestamp-millis"}},
    {"name": "order_id",   "type": "string"},
    {
      "name": "items",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "OrderItem",
          "fields": [
            {"name": "product_id", "type": "string"},
            {"name": "zone_id",    "type": "string"},
            {"name": "quantity",   "type": "long"}
          ]
        }
      }
    }
  ]
}
