{
  "type": "record",
  "name": "ProductReserved",
  "namespace": "warehouse.events.v1",
  "doc": "Резервирование товара под заказ",
  "fields": [
    {"name": "event_id",   "type": "string"},
    {"name": "event_type", "type": "string", "default": "PRODUCT_RESERVED"},
    {"name": "timestamp",  "type": {"type": "long", "logicalType": "timestamp-millis"}},
    {"name": "product_id", "type": "string"},
    {"name": "zone_id",    "type": "string"},
    {"name": "quantity",   "type": "long"},
    {"name": "order_id",   "type": ["null", "string"], "default": null}
  ]
}
